name: Build
on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git unzip openjdk-8-jdk
          pip install buildozer cython

      - name: Install Android SDK and Tools
        run: |
          sudo apt-get install -y wget
          mkdir -p $HOME/Android/Sdk
          cd $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          mkdir -p tools/bin
          mv cmdline-tools/* tools/bin/
          yes | tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --update
          yes | tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"
          
      - name: Ensure Buildozer.spec file exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "buildozer.spec file not found!"
            exit 1
          else
            echo "buildozer.spec file found."
          fi

      - name: Build with Buildozer
        run: buildozer android debug
        working-directory: ./  # Ensure this matches the location of buildozer.spec

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk  # Adjust the path if necessary
