name: Build
on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git unzip openjdk-8-jdk
          pip install buildozer cython

      - name: Ensure Buildozer.spec file exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "buildozer.spec file not found!"
            exit 1
          else
            echo "buildozer.spec file found."
          fi

      - name: Build with Buildozer
        run: buildozer android debug
        working-directory: ./  # Ensure this matches the location of buildozer.spec

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk  # Adjust the path if necessary
